version: '3.8'

services:
  postgresdb:
    image: postgres:15.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=teslodb
    
    
    